Add F2003 intrinsics for FLUSH; use F95 CPU_TIME when available. The rest of the source code can now be compiled using -std=f95.
git-svn-id: https://svn.code.sf.net/p/auto-07p/code/trunk/auto/07p@1652 ee9e63dd-6847-0410-88cd-b7174c777ff7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3318,8 +3318,42 @@ ac_link='$FC -o conftest$ac_exeext $FCFLAGS $LDFLAGS $ac_fcflags_srcext conftest
 ac_compiler_gnu=$ac_cv_fc_compiler_gnu
 
 # ifc needs -Vaxlib to use FLUSH and ETIME.
-unset COMPAT
+COMPAT="f2003"
 cat >conftest.$ac_ext <<_ACEOF
+
+  program main
+  real t
+  print *,'hello'
+  flush(6)
+  call cpu_time(t)
+  end
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_fc_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	 COMPAT="unix"
+ cat >conftest.$ac_ext <<_ACEOF
 
   program main
   real t(2),r,etime
@@ -3386,7 +3420,11 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	FCFLAGS=$tmp;COMPAT="../lib/compat.o"
+	FCFLAGS=$tmp;COMPAT="compat"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
