Improve moc detection (just use $PATH and $QTDIR, and warn if not available)
git-svn-id: https://svn.code.sf.net/p/auto-07p/code/trunk/auto/07p@1667 ee9e63dd-6847-0410-88cd-b7174c777ff7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7495,6 +7495,11 @@ if (test x$HAVE_SOXT_CONFIG = "xtrue" || test x$HAVE_SOQT_CONFIG = "xtrue" || \
         if ( echo $SOXT_LIBS | grep QtGui > /dev/null ); then
             MOCNAMES="moc-qt4 moc"
         fi
+	if test -n "$QTDIR"; then
+	    mocpath=$QTDIR/bin:$PATH
+	else
+	    mocpath=$PATH
+	fi
 	for ac_prog in $MOCNAMES
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -7510,9 +7515,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="$QTDIR/bin:/usr/lib/qt2/bin:/usr/bin:/usr/X11R6/bin:/usr/lib/qt/bin:/usr/local/qt/bin:$PATH
-	"
-for as_dir in $as_dummy
+for as_dir in $mocpath
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -7541,11 +7544,22 @@ fi
 
   test -n "$MOC" && break
 done
-test -n "$MOC" || MOC="$QTDIR/bin/moc"
+test -n "$MOC" || MOC="false"
 
-	SOXT_OBJS="gmainqt.moc.o gmainqt.o"
-	SOXT_OBJS_R3B="../gmainqt.moc.o gmainqt.o"
-	X_CFLAGS="$X_CFLAGS -DUSE_SOQT"
+	if test x"$MOC" = x"false"; then
+	    { echo "$as_me:$LINENO: WARNING: ''moc'' Qt preprocessor not found" >&5
+echo "$as_me: WARNING: ''moc'' Qt preprocessor not found" >&2;}
+	    if test -z "$QTDIR"; then
+		{ echo "$as_me:$LINENO: WARNING: \"(QTDIR environment variable not set)\"" >&5
+echo "$as_me: WARNING: \"(QTDIR environment variable not set)\"" >&2;}
+	    fi
+	    PLAUT04=""
+	    PLAUT04_TEST="no"
+	else
+	    SOXT_OBJS="gmainqt.moc.o gmainqt.o"
+	    SOXT_OBJS_R3B="../gmainqt.moc.o gmainqt.o"
+	    X_CFLAGS="$X_CFLAGS -DUSE_SOQT"
+	fi
     fi
 else
     PLAUT04=""
